site_name: XO Core Docs
docs_dir: docs
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Architecture:
      - XO Vault Ecosystem: architecture.md
  - Usage:
      - Getting Started: getting-started.md
      - Vault CLI Reference: vault-cli.md